spring:
  datasource:
    url: jdbc:mysql://localhost:3306/expense_manager?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: z30420qwas@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        highlight_sql: true
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: localhost
      port: 6379

  jwt:
    secret-key: kdosoxikjkljaxdkfjioqwurqioweurkxcvbklsdfjgoiweurtkoljqwelkrja
    access-expiration-time: 1800000
    refresh-expiration-time: 604800000
    authorities-key: "roles"
    token-prefix: "Bearer "

springdoc:
  use-fqn: true
  api-docs:
    resolve-method-annotations: true
  swagger-ui:
    disable-swagger-default-url: true
